<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Manali & Solang Valley',
                'country' => 'India',
                'state_region' => 'Himachal Pradesh',
                'cover_image' => 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Snow-capped Himalayan peaks, pine forests, adventure sports, and scenic valley views.',
                'description' => 'Manali is a high-altitude Himalayan resort town in India’s northern Himachal Pradesh state. It has a reputation as a backpacking center and honeymoon destination. Set on the Beas River, it’s a gateway for skiing in the Solang Valley and trekking in Parvati Valley.',
                'best_time_to_visit' => 'October to June',
                'popular_attractions' => 'Solang Valley, Rohtang Pass, Hadimba Temple, Jogini Waterfall, Mall Road',
                'travel_info' => 'Nearest Airport: Bhuntar (Kullu) Airport (50km). Volvo buses available daily from Delhi.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Leh Ladakh Expedition',
                'country' => 'India',
                'state_region' => 'Jammu & Kashmir',
                'cover_image' => 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'High mountain passes, crystal Pangong Tso lake, ancient monasteries, and magnetic hills.',
                'description' => 'Ladakh is a region administered by India as a union territory, located in the highest mountain range in the world. Renowned for remote mountain beauty and culture, it is often referred to as Little Tibet.',
                'best_time_to_visit' => 'May to September',
                'popular_attractions' => 'Pangong Tso, Nubra Valley, Khardung La Pass, Magnetic Hill, Diskit Monastery',
                'travel_info' => 'Fly directly into Kushok Bakula Rimpochee Airport (IXL) in Leh. Acclimatization for 24-48 hours is mandatory.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Goa Beaches & Nightlife',
                'country' => 'India',
                'state_region' => 'Goa',
                'cover_image' => 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Golden sands, nightlife, Portuguese architecture, water sports, and beach shacks.',
                'description' => 'Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony is evident in its preserved 17th-century churches and tropical spice plantations.',
                'best_time_to_visit' => 'November to February',
                'popular_attractions' => 'Baga Beach, Calangute, Dudhsagar Waterfalls, Fort Aguada, Panaji Old Goa',
                'travel_info' => 'Nearest Airport: Dabolim (GOI) or Mopa (GOX). Well connected by rail and expressways.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Kerala Backwaters & Tea Gardens',
                'country' => 'India',
                'state_region' => 'Kerala',
                'cover_image' => 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Serene houseboat cruises, tea gardens of Munnar, Ayurvedic wellness, and spice plantations.',
                'description' => 'Kerala, a state on India’s tropical Malabar Coast, has nearly 600km of Arabian Sea shoreline. It’s known for its palm-lined beaches and backwaters, a network of canals.',
                'best_time_to_visit' => 'September to March',
                'popular_attractions' => 'Alleppey Houseboats, Munnar Tea Gardens, Thekkady Wildlife Sanctuary, Kovalam Beach',
                'travel_info' => 'Cochin International Airport (COK) or Trivandrum International Airport (TRV).',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Dubai Luxury Skyline',
                'country' => 'United Arab Emirates',
                'state_region' => 'Emirate of Dubai',
                'cover_image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Futuristic skyscrapers, luxury shopping malls, desert safaris, and world-class dining.',
                'description' => 'Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture, and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline.',
                'best_time_to_visit' => 'November to April',
                'popular_attractions' => 'Burj Khalifa, Dubai Mall, Desert Safari, Palm Jumeirah, Dubai Marina',
                'travel_info' => 'Dubai International Airport (DXB). Visa on arrival available for eligible passport holders.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Bali Island Escape',
                'country' => 'Indonesia',
                'state_region' => 'Bali Province',
                'cover_image' => 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Volcanic mountains, iconic rice paddies, coral reefs, and sacred Hindu temples.',
                'description' => 'Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple.',
                'best_time_to_visit' => 'April to October',
                'popular_attractions' => 'Ubud Rice Terraces, Tanah Lot Temple, Nusa Penida Island, Kuta Beach, Mount Batur',
                'travel_info' => 'Ngurah Rai International Airport (DPS) in Denpasar.',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Newly Added North-East & Eastern Himalayan Destinations
            [
                'name' => 'Assam - Kaziranga & Brahmaputra',
                'country' => 'India',
                'state_region' => 'Assam',
                'cover_image' => 'https://images.unsplash.com/photo-1622308644420-a2491a629b35?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'One-horned rhinoceros safaris at Kaziranga, tea garden estates, Brahmaputra river cruises, and Kamakhya Temple.',
                'description' => 'Assam is a northeastern state in India known for its wildlife, silk bazaars, and world-renowned tea plantations. Kaziranga National Park is home to two-thirds of the world’s great one-horned rhinoceroses.',
                'best_time_to_visit' => 'October to April',
                'popular_attractions' => 'Kaziranga National Park, Kamakhya Temple, Majuli River Island, Jorhat Tea Estates, Manas Sanctuary',
                'travel_info' => 'Lokpriya Gopinath Bordoloi International Airport (GAU) in Guwahati. Well connected by North-East Express trains.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Arunachal Pradesh & Tawang Monastery',
                'country' => 'India',
                'state_region' => 'Arunachal Pradesh',
                'cover_image' => 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'High altitude Tawang Monastery, Sela Pass snow mountain views, Ziro music valley, and pristine alpine lakes.',
                'description' => 'Known as the Land of the Dawn-Lit Mountains, Arunachal Pradesh is India’s easternmost state featuring majestic snow-capped Himalayan peaks, 400-year-old Buddhist monasteries, and rich tribal heritage.',
                'best_time_to_visit' => 'October to April',
                'popular_attractions' => 'Tawang Monastery, Sela Pass (13,700 ft), Madhuri Lake, Ziro Valley, Bomdila Monastery',
                'travel_info' => 'Fly to Tezpur or Guwahati Airport, followed by scenic hill drive via Bhalukpong. Inner Line Permit (ILP) required.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Meghalaya - Abode of Clouds',
                'country' => 'India',
                'state_region' => 'Meghalaya',
                'cover_image' => 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Living root bridges of Cherrapunji, crystal-clear Umngot river in Dawki, Nohkalikai waterfalls, and Shillong peak.',
                'description' => 'Meghalaya is a picturesque hill state in northeastern India. Renowned worldwide for Cherrapunji and Mawsynram (the wettest places on Earth), living bio-engineered root bridges, and crystal turquoise rivers.',
                'best_time_to_visit' => 'September to May',
                'popular_attractions' => 'Double Decker Living Root Bridge, Dawki Umngot River, Cherrapunji Waterfalls, Mawlynnong Cleanest Village, Shillong Peak',
                'travel_info' => 'Nearest Airport: Shillong Airport (Umroi) or Guwahati Airport (120 km). Shared and private taxis available.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Nagaland & Hornbill Cultural Valley',
                'country' => 'India',
                'state_region' => 'Nagaland',
                'cover_image' => 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Vibrant Hornbill Festival, Kohima war memorial, scenic Dzukou Valley trekking, and rich tribal heritage villages.',
                'description' => 'Nagaland is a mountainous state in northeastern India bordering Myanmar. Home to diverse indigenous Naga tribes, it is celebrated worldwide for the annual December Hornbill Festival and the emerald Dzukou Valley.',
                'best_time_to_visit' => 'October to May',
                'popular_attractions' => 'Kisama Heritage Village (Hornbill Festival Ground), Kohima War Cemetery, Dzukou Valley, Khonoma Green Village',
                'travel_info' => 'Nearest Airport and Railhead: Dimapur Airport (DMU). Inner Line Permit (ILP) required for all visitors.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Manipur & Floating Loktak Lake',
                'country' => 'India',
                'state_region' => 'Manipur',
                'cover_image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'World’s only floating national park at Loktak Lake, Keibul Lamjao sangai deer sanctuary, and historic Kangla Fort.',
                'description' => 'Known as the Jewel of India, Manipur features the unique freshwater Loktak Lake with floating phumdis, the endangered Sangai dancing deer, rich classical Manipuri dance heritage, and lush green hills.',
                'best_time_to_visit' => 'October to April',
                'popular_attractions' => 'Loktak Lake, Keibul Lamjao National Park, Kangla Fort Imphal, Ima Keithel (All-Women Market), Moreh Border Market',
                'travel_info' => 'Imphal Bir Tikendrajit International Airport (IMF) has direct flight connections to Kolkata, Guwahati, and Delhi.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Mizoram - Blue Mountain Hills',
                'country' => 'India',
                'state_region' => 'Mizoram',
                'cover_image' => 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Rolling evergreen hills, Phawngpui Blue Mountain peak, Vantawng waterfalls, and peaceful Mizoram bamboo culture.',
                'description' => 'Mizoram is a land of rolling evergreen hills, rivers, lakes, and deep valleys in northeastern India. Renowned for its pleasant climate, vibrant bamboo crafts, and breathtaking hilltop panoramic vistas.',
                'best_time_to_visit' => 'October to March',
                'popular_attractions' => 'Phawngpui Blue Mountain Peak, Reiek Heritage Village, Vantawng Waterfalls, Tamdil Lake, Solomon’s Temple Aizawl',
                'travel_info' => 'Lengpui Airport (AJL) in Aizawl connects directly to Kolkata and Guwahati. Inner Line Permit (ILP) required.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Tripura & Ujjayanta Royal Palace',
                'country' => 'India',
                'state_region' => 'Tripura',
                'cover_image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Magnificent Ujjayanta Palace, Neermahal floating water palace, and ancient Unakoti rock sculptures.',
                'description' => 'Tripura is a hilly state in northeast India surrounded on three sides by Bangladesh. It is home to regal Tripura Manikya dynasty palaces, ancient giant rock-cut carvings at Unakoti, and lush wildlife sanctuaries.',
                'best_time_to_visit' => 'October to March',
                'popular_attractions' => 'Ujjayanta Palace Agartala, Neermahal Water Palace, Unakoti Rock Carvings, Sepahijala Wildlife Sanctuary, Tripura Sundari Temple',
                'travel_info' => 'Maharaja Bir Bikram Airport (IXA) in Agartala. Daily rail connectivity via Rajdhani and Express trains.',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Sikkim - Gangtok & Nathula Pass',
                'country' => 'India',
                'state_region' => 'Sikkim',
                'cover_image' => 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'Views of Mt. Kanchenjunga, high altitude Tsomgo Lake, Nathula Indo-China border pass, and Rumtek Monastery.',
                'description' => 'Sikkim is a Himalayan paradise in northeastern India bordered by Bhutan, Tibet, and Nepal. Home to glaciers, alpine flower meadows, and 8,586m Mt. Kanchenjunga (the world’s third-highest peak).',
                'best_time_to_visit' => 'March to June & October to December',
                'popular_attractions' => 'Tsomgo Lake, Nathula Pass (14,140 ft), Gurudongmar Lake, Yumthang Valley of Flowers, Rumtek Monastery, Pelling Skywalk',
                'travel_info' => 'Pakyong Airport (PYG) or Bagdogra Airport (IXB) (125 km). Nearest railway station: NJP (New Jalpaiguri).',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Darjeeling Tea Gardens & Tiger Hill',
                'country' => 'India',
                'state_region' => 'West Bengal',
                'cover_image' => 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
                'short_description' => 'UNESCO World Heritage Toy Train, Tiger Hill Kanchenjunga sunrise view, and world-famous Darjeeling tea estates.',
                'description' => 'Darjeeling is a famous hill resort in West Bengal state set in the Himalayan foothills. Renowned for the narrow-gauge Darjeeling Himalayan Railway (Toy Train), panoramic views of Mt. Kanchenjunga, and organic tea estates.',
                'best_time_to_visit' => 'October to May',
                'popular_attractions' => 'Tiger Hill Sunrise, Darjeeling Himalayan Railway Toy Train, Happy Valley Tea Estate, Batasia Loop, Himalayan Mountaineering Institute',
                'travel_info' => 'Bagdogra Airport (IXB) (68 km) or New Jalpaiguri Railway Station (NJP) (70 km). Shared and private taxis available.',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($destinations as $dest) {
            $dest['slug'] = Str::slug($dest['name']);
            Destination::updateOrCreate(['slug' => $dest['slug']], $dest);
        }
    }
}
